### ISSUE TITLE
To Do

### ISSUE THREAD

**Issue by Sheepzez** [Sheepzez/Matrixonator-Java#1]
- [x] Add functionality to add matrices to main list.
- [x] Add functionality to edit matrices in main list. (Added by 03f1a5ada58597a71a0f619a05134f0f991d6a54)
- [x] Add functionality to add data to matrices. (Matrices can't be later changed)
- [ ] Add functionality to calculate properties of matrix 
  - [x] Reduced Row Echelon Form
  - [x] Determinant of matrix
  - [x] Eigenvalues
  - [ ] Bases of eigenspaces
  - [x] Trace
  - [x] Inverse
- [x] Add functionality to perform calculations with matrices (addition, multiplication)
- [x] Add functionality to save matrices to disk, for persistence of data
- [x] Add full Java-Doc of application, and host on GitHub Pages.

**Comment by projectgoav** [comment]
We can tick off save/persistence feature!

**Comment by Sheepzez** [comment]
Inverse and determinant methods completed as of be119a06a2b3d03599ee2a4f77538e53e1a35b98.

**Comment by Sheepzez** [comment]
Since eigenvalues of 2x2 matrices was introduced in 8c0648a148a69d951f908213e2b9a0c99a912b45 I am considering this To-Do list completed. Although eigenvalues of nxn matrices still needs to be implemented, and eigenspaces/vectors too. These two topics are very complex comparatively, and should be considered separate issues as themselves. For now, these topics are closed.
