### ISSUE TITLE
Editable Code

### ISSUE THREAD

**Issue by projectgoav** [Sheepzez/Matrixonator-Java#28]
Since we've added Travis to the project the code has moved from the standard src folder.
Do we now edit code from  <b>src/main/java/ ... </b> ? or still use <b> src/ijordan/Matrixonator/... </b>

**Comment by Sheepzez** [comment]
There is no code in SRC/ijordan/. That folder doesn't exist any more. So the answer to your question is yes :)

**Comment by projectgoav** [comment]
I forgot to commit my merge and so it's kept both sets of code! Thank you
