### ISSUE TITLE
Help won't reopen after being closed

### ISSUE THREAD

**Issue by Sheepzez** [Sheepzez/Matrixonator-Java#39]
To reproduce:
- Launch MainApp
- Open Help section
- Close Help section via any method that is not Alt+F4/File menu.
- Attempt to open Help section again.

When you attempt to open the Help section again, nothing happens. No errors, no alerts.

**Comment by projectgoav** [comment]
Issue fixed in 5bd1153 *(Still too PR)*

**Comment by projectgoav** [comment]
Issue fixed in 0d0d708
