### ISSUE TITLE
Failing tests for calculating Reduced Row Echelon Form (RREF) of matrix

### ISSUE THREAD

**Issue by Sheepzez** [Sheepzez/Matrixonator-Java#6]
First failed test is testMatrixReduceNegative() which gives the following exception when calcuting RREF of { { 1, 2, 1 }, { -2, -3, 1 }, { 3, 5, 0 } }. The correct result is given [here](http://www.wolframalpha.com/input/?i=row+reduce+%7B+%7B+1%2C+2%2C+1+%7D%2C+%7B+-2%2C+-3%2C+1+%7D%2C+%7B+3%2C+5%2C+0+%7D+%7D).

java.lang.ArrayIndexOutOfBoundsException: 3
	at ijordan.matrixonator.model.Matrix.stepOne(Matrix.java:175)
	at ijordan.matrixonator.model.Matrix.stepOne(Matrix.java:184)
	at ijordan.matrixonator.model.Matrix.reducedEchelonForm(Matrix.java:125)
	at ijordan.matrixonatorTest.MatrixTest.testMatrixReduceNegative(MatrixTest.java:120)
	...

The second failed test gives no exception, just an incorrect result. The solution given by the method is [[3.1305550697556894E56, 1.4903230184787869E57, 1.693570856450139E58, 1.1369543976996965E58], [-4.14862777762012E52, -1.9749837758229463E53, -2.244328862416484E54, -1.5066978510467205E54], [-6.3998734312946644E44, -3.0467052894723863E45, -3.462210019214276E46, -2.324304821444897E46], [-2.2234667295396705E29, -1.0584971591358462E30, -1.2028532862476555E31, -8.075182259887142E30]], whereas the correct solution is given [here](http://www.wolframalpha.com/input/?i=row+reduce+%7B+%7B+1586%2C+7546%2C+85746%2C+57564+%7D%2C+%7B+756%2C+374%2C+385%2C+0+%7D%2C+%09%7B+8765%2C+123%2C+765%2C+234+%7D%2C+%7B+5736%2C+4736%2C+27364%2C+5+%7D+%7D).

Both of these failures are very likely due to incorrect code in the method calculating the RREF.

**Comment by Sheepzez** [comment]
Found some information relating to this issue. 
The code that this algorithm stems from in the original [Matrixonator repo](https://github.com/Sheepzez/The-Matrixonator) is actually bugged as well for the same test data. So solving this issue here, will likely also be related to the issue in that Python code.

**Comment by projectgoav** [comment]
This issue seems to have been fixed with your most recent commit.

**Comment by Sheepzez** [comment]
Indeed, thank you for pointing this out. Solved by a32cffb2c34947987b79c19715d76379bbe7a832.
