### ISSUE TITLE
Properties not working

### ISSUE THREAD

**Issue by projectgoav** [Sheepzez/Matrixonator-Java#9]
None of the property set methods are working correctly. While debugging the Matrix.load() method, the properties through:

[name]Property().set([value]); or set[name]([value]); don't update the values in the Matrix class.

Am I calling these set methods properly?

![capture](https://cloud.githubusercontent.com/assets/6363155/5669120/de47d844-976c-11e4-8da2-1439bdc6b381.PNG)

**Comment by Sheepzez** [comment]
I think the issue may lie in the fact that those are currently set to 'final' and are therefore immutable. I would suggest just using the constructor to the setting of these. Is there a reason why the constructor isn't suitable?

**Comment by projectgoav** [comment]
Nah, I was just lazy! I'll add another constructor and move load into that, cause it wont be needed as a method? It wont let you call .load from constructor

**Comment by Sheepzez** [comment]
Why not use the (existing) constructor to create the new matrices being loaded in?

**Comment by projectgoav** [comment]
There is no constructor with options to set the created date and so was going to add a constructor to allow that?

**Comment by projectgoav** [comment]
Edit: I've put it into a constructor requiring a filename parameter.
